name: Publish Data Sync Azure Func

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Add Garage Group NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }}
        -n ggroupp
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    - name: Test platfrom dataverse to sql sync
      run: dotnet test

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Add Garage Group NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }}
        -n ggroupp
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    - name: Restore sync func
      run: dotnet restore ./src/app/data-sync/AzureFunc/AzureFunc.csproj

    - name: Build sync func
      run: dotnet build ./src/app/data-sync/AzureFunc/AzureFunc.csproj --no-restore  -c Release

    - name: Publish sync func
      run: dotnet publish ./src/app/data-sync/AzureFunc/AzureFunc.csproj --no-build  -c Release --output ./publish

    - name: Get version
      id: get_version
      run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

    - name: Archive publish folder
      run: zip -r ggroupp-platform-dataverse-to-sql-azure-func-${{ env.version }}.zip ./publish

    - name: Upload build output to Azure Blob Storage
    - uses: actions/checkout@v3
    - uses: bacongobbler/azure-blob-storage-upload@v3
      with:
        source_dir: ggroupp-platform-dataverse-to-sql-azure-func-${{ env.version }}.zip
        container_name: startifactblob
        connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}