name: Publish Move Console App

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Add Garage Group NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }}
        -n ggroupp
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    - name: Test platfrom dataverse to sql sync
      run: dotnet test

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Add Garage Group NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }}
        -n ggroupp
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    - name: Restore console app
      run: dotnet restore ./src/app/data-move/Console/Console.csproj

    - name: Build console app
      run: dotnet build ./src/app/data-move/Console/Console.csproj --no-restore  -c Release

    - name: Publish console app
      run: dotnet publish ./src/app/data-move/Console/Console.csproj --no-build  -c Release --output ./ggroupp-platform-dataverse-to-sql-console-${{ env.version }}

    - name: Get version
      id: get_version
      run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

    - name: Upload build output to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0
      with:
        source_dir: ggroupp-platform-dataverse-to-sql-console-${{ env.version }}
        container_name: startifactblob
        connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}