name: Publish Data Sync Azure Func And Console App

on:
  page_build:
  release:
    types:
    - created

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Add Garage Group NuGet Source
        run: >
          dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
          -n garage
          -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
          -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
          --store-password-in-clear-text

      - name: Test platfrom dataverse to sql sync
        run: dotnet test

  publish-version:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Add Garage Group NuGet Source
        run: >
          dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
          -n garage
          -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
          -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
          --store-password-in-clear-text

      - name: Restore sync func
        run: dotnet restore ./src/app/data-sync/AzureFunc/AzureFunc.csproj

      - name: Build sync func
        run: dotnet build ./src/app/data-sync/AzureFunc/AzureFunc.csproj --no-restore  -c Release

      - name: Publish sync func
        run: dotnet publish ./src/app/data-sync/AzureFunc/AzureFunc.csproj --no-build  -c Release --output ./buildFunc

      - name: Restore console app
        run: dotnet restore ./src/app/data-move/Console/Console.csproj

      - name: Build console app
        run: dotnet build ./src/app/data-move/Console/Console.csproj --no-restore  -c Release

      - name: Publish console app
        run: dotnet publish ./src/app/data-move/Console/Console.csproj --no-build  -c Release --output ./buildConsole

      - name: Get version
        id: get_version
        run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Archive sync func publish folder
        run: |
          cd ./buildFunc
          zip -r garage-platform-dataverse-to-sql-azure-func-net8-${{ env.version }}.zip ./

      - name: Archive console app publish folder
        run: |
          cd ./buildConsole
          zip -r garage-platform-dataverse-to-sql-console-app-net8-${{ env.version }}.zip ./

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ARTIFACT }}

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload \
              --container-name artifacts \
              --file ./buildFunc/garage-platform-dataverse-to-sql-azure-func-net8-${{ env.version }}.zip \
              --account-name startifactblob \
              --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }} &&

            az storage blob upload \
              --container-name artifacts \
              --file ./buildConsole/garage-platform-dataverse-to-sql-console-app-net8-${{ env.version }}.zip \
              --account-name startifactblob \
              --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }} \
        env:
          AZURE_STORAGE_ACCOUNT: startifactblob

      - name: Azure Logout
        uses: azure/CLI@v1
        with:
          inlineScript: az logout

  publish-latest:
    if: github.event.release.prerelease == false
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Add Garage Group NuGet Source
        run: >
          dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
          -n garage
          -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
          -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
          --store-password-in-clear-text

      - name: Restore sync func
        run: dotnet restore ./src/app/data-sync/AzureFunc/AzureFunc.csproj

      - name: Build sync func
        run: dotnet build ./src/app/data-sync/AzureFunc/AzureFunc.csproj --no-restore  -c Release

      - name: Publish sync func
        run: dotnet publish ./src/app/data-sync/AzureFunc/AzureFunc.csproj --no-build  -c Release --output ./buildFunc

      - name: Restore console app
        run: dotnet restore ./src/app/data-move/Console/Console.csproj

      - name: Build console app
        run: dotnet build ./src/app/data-move/Console/Console.csproj --no-restore  -c Release

      - name: Publish console app
        run: dotnet publish ./src/app/data-move/Console/Console.csproj --no-build  -c Release --output ./buildConsole

      - name: Archive sync func publish folder
        run: |
          cd ./buildFunc
          zip -r garage-platform-dataverse-to-sql-azure-func-net8-latest.zip ./

      - name: Archive console app publish folder
        run: |
          cd ./buildConsole
          zip -r garage-platform-dataverse-to-sql-console-app-net8-latest.zip ./

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ARTIFACT }}
      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload \
              --container-name artifacts \
              --file ./buildFunc/garage-platform-dataverse-to-sql-azure-func-net8-latest.zip \
              --account-name startifactblob \
              --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }} &&

            az storage blob upload \
              --container-name artifacts \
              --file ./buildConsole/garage-platform-dataverse-to-sql-console-app-net8-latest.zip \
              --account-name startifactblob \
              --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }} \
        env:
          AZURE_STORAGE_ACCOUNT: startifactblob

      - name: Azure Logout
        uses: azure/CLI@v1
        with:
          inlineScript: az logout